# Generated by scripts/distribution.py from the release SHA256SUMS; do not edit.
class Anytopdf < Formula
  desc "Convert media and documents into searchable, RAG-friendly PDFs"
  homepage "https://github.com/adeelahmad/anytopdf-rs"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.2.0/anytopdf-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "ade5bc88385bc8c9f44f0c92c496d8954aef20ab6b38eebeab2de1ce114fc911"
    end
    on_intel do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.2.0/anytopdf-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "7095bc484e3917da8e9e5fae36b901ac5fbc3dadc27a79535068f62e8619bad5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.2.0/anytopdf-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4f1540383cdcec1fcf9dd2d60f9c0c7ec7d3f0a07e35809ddac121b48ae886ed"
    end
    on_intel do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.2.0/anytopdf-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "cb4021b6c658197aae8b53debb672afec667e18993236184f0b03b9567d1b910"
    end
  end

  def install
    bin.install "anytopdf"
    libexec.install "plugins"
    doc.install Dir["*.md"]
  end

  def caveats
    <<~EOS
      Video, metadata, OCR and transcription use optional providers.
      Install the ones you need:
        brew install ffmpeg exiftool tesseract whisper-cpp
      Bundled runtime plugins are opt-in. To transcribe audio and video with
      anytopdf-plugin-whisper and tag the sentiment and tone of text with
      anytopdf-plugin-sentiment, add to your shell profile:
        export ANYTOPDF_PLUGIN_PATH="#{opt_libexec}/plugins"
        export ANYTOPDF_WHISPER_MODEL=/path/to/ggml-base.en.bin
      Then run `anytopdf doctor` to check what is available.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anytopdf --version")
    assert_match "anytopdf.capabilities/1",
                 shell_output("#{bin}/anytopdf --no-plugins capabilities --json")
    plugins = Dir["#{libexec}/plugins/anytopdf-plugin-*"]
    refute_empty plugins
    plugins.each do |plugin|
      assert_match "\"protocol\":1", shell_output("#{plugin} --anytopdf-manifest")
    end
  end
end
