# Generated by scripts/distribution.py from the release SHA256SUMS; do not edit.
class Anytopdf < Formula
  desc "Convert media and documents into searchable, RAG-friendly PDFs"
  homepage "https://github.com/adeelahmad/anytopdf-rs"
  version "0.3.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.3.0/anytopdf-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "29751b5a916a328cafdad52af19a6415a9b72c36ddc8784c8c11bbd936d435c3"
    end
    on_intel do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.3.0/anytopdf-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "71b9170b75ac6b1783e91f15aaef9fba826d0bda5af7dbb6bbc0efcc9445f2bc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.3.0/anytopdf-0.3.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9c6cc307a3e6dc7e7e44c390176ce62e7b77ebad640ea74c569272104a79f6dd"
    end
    on_intel do
      url "https://github.com/adeelahmad/anytopdf-rs/releases/download/v0.3.0/anytopdf-0.3.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2a789bf099cd14b5f68a147b44170d3f243299565b09b93b3a3329811a2492c0"
    end
  end

  def install
    bin.install "anytopdf"
    libexec.install "plugins"
    doc.install Dir["*.md"]
  end

  def caveats
    <<~EOS
      Video, metadata, OCR and transcription use optional providers.
      Install the ones you need:
        brew install ffmpeg exiftool tesseract whisper-cpp
      Bundled runtime plugins in #{opt_libexec}/plugins are found
      automatically and turn on once they have what they need. Run
        anytopdf setup whisper
      for speech to text, and `anytopdf capabilities` to see how to turn
      on the others (object detection, CLIP scene tags, face recognition,
      vision-model captions). Set ANYTOPDF_PLUGIN_PATH to that folder to
      run every bundled plugin even when it reports something missing.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anytopdf --version")
    assert_match "anytopdf.capabilities/1",
                 shell_output("#{bin}/anytopdf --no-plugins capabilities --json")
    plugins = Dir["#{libexec}/plugins/anytopdf-plugin-*"]
    refute_empty plugins
    plugins.each do |plugin|
      assert_match "\"protocol\":1", shell_output("#{plugin} --anytopdf-manifest")
    end
  end
end
