#!/usr/bin/env python3
"""Builds crates/anytopdf-builtin/data/geonames-cities1000.tsv.gz.

The table backs offline reverse geocoding and place-name matching in the
built-in location enricher. It is derived from GeoNames (https://www.geonames.org/,
CC BY 4.0) as packaged by:

  - geonamescache (pip): data/cities1000.json and data/countries.json
  - reverse_geocoder (pip sdist): rg_cities1000.csv, used only for the
    first-level administrative division names, which geonamescache lacks

Usage:
  pip download --no-deps geonamescache
  pip download --no-deps --no-binary :all: reverse_geocoder
  # unpack both, then
  python3 scripts/build-geonames.py <cities1000.json> <countries.json> \
      <rg_cities1000.csv> crates/anytopdf-builtin/data/geonames-cities1000.tsv.gz

Output lines (UTF-8, tab separated, '#' starts a comment):
  C <cc> <country name>
  A <cc> <admin1 code> <admin1 name>
  P <name> <lat*1e3> <lon*1e3> <cc> <admin1 code> <population>

Coordinates keep three decimals (about 110 m), enough to name the nearest town.
"""

import collections
import csv
import gzip
import json
import sys


def clean(text):
    return " ".join(str(text).replace("\t", " ").split())


def main(cities_path, countries_path, rg_path, out_path):
    with open(cities_path, encoding="utf-8") as f:
        cities = json.load(f)
    with open(countries_path, encoding="utf-8") as f:
        countries = json.load(f)

    rg = {}
    with open(rg_path, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            key = (row["cc"], round(float(row["lat"]), 4), round(float(row["lon"]), 4))
            rg[key] = row["admin1"]

    votes = collections.defaultdict(collections.Counter)
    for city in cities.values():
        key = (city["countrycode"], round(city["latitude"], 4), round(city["longitude"], 4))
        name = rg.get(key)
        if name and city.get("admin1code"):
            votes[(city["countrycode"], city["admin1code"])][name] += 1
    admin1 = {k: c.most_common(1)[0][0] for k, c in votes.items()}

    lines = [
        "# anytopdf offline gazetteer: GeoNames cities with population >= 1000.",
        "# Contains data from GeoNames (https://www.geonames.org/), licensed CC BY 4.0.",
        "# Generated by scripts/build-geonames.py; do not edit by hand.",
    ]
    for cc in sorted(countries):
        lines.append(f"C\t{cc}\t{clean(countries[cc]['name'])}")
    for (cc, code) in sorted(admin1):
        lines.append(f"A\t{cc}\t{clean(code)}\t{clean(admin1[(cc, code)])}")
    # Grouping by country and region compresses far better than any other order.
    rows = sorted(
        cities.values(),
        key=lambda c: (c["countrycode"], c.get("admin1code") or "", c["name"], c["geonameid"]),
    )
    for c in rows:
        lines.append(
            "P\t{}\t{}\t{}\t{}\t{}\t{}".format(
                clean(c["name"]),
                round(c["latitude"] * 1e3),
                round(c["longitude"] * 1e3),
                c["countrycode"],
                clean(c.get("admin1code") or ""),
                int(c["population"] or 0),
            )
        )
    data = ("\n".join(lines) + "\n").encode("utf-8")
    with open(out_path, "wb") as f:
        # mtime=0 keeps the output byte-for-byte reproducible.
        with gzip.GzipFile(fileobj=f, mode="wb", compresslevel=9, mtime=0, filename="") as gz:
            gz.write(data)
    print(f"{len(countries)} countries, {len(admin1)} admin1, {len(rows)} places -> {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    main(*sys.argv[1:])
