#!/usr/bin/env python3
"""Render the Homebrew formula and Scoop manifest for a published release.

Reads the release's SHA256SUMS (written by the release workflow) and writes
anytopdf.rb and anytopdf.json. Publishing them to a tap or bucket is a separate,
manual step described in docs/distribution.md.
"""
import argparse
import json
from pathlib import Path
import re
import tomllib

ROOT = Path(__file__).resolve().parents[1]
NAME = "anytopdf"
# Homebrew (os, arch) and Scoop architecture for each release target.
HOMEBREW = {
    ("macos", "arm"): "aarch64-apple-darwin",
    ("macos", "intel"): "x86_64-apple-darwin",
    ("linux", "arm"): "aarch64-unknown-linux-musl",
    ("linux", "intel"): "x86_64-unknown-linux-musl",
}
SCOOP = {"64bit": "x86_64-pc-windows-msvc"}
# Runtime plugins shipped in each archive's plugins/ folder. They stay opt-in:
# anytopdf only runs them once ANYTOPDF_PLUGIN_PATH names that folder.
PLUGINS = ["anytopdf-plugin-whisper"]
SEMVER = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?")


def workspace_package(root=ROOT):
    return tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))["workspace"]["package"]


def cli_description(root=ROOT):
    package = tomllib.loads((root / "crates/anytopdf-cli/Cargo.toml").read_text(encoding="utf-8"))
    return package["package"]["description"]


def archive_name(version, target):
    suffix = "zip" if "windows" in target else "tar.gz"
    return f"{NAME}-{version}-{target}.{suffix}"


def read_checksums(path):
    digests = {}
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        match = re.fullmatch(r"([0-9a-f]{64})  ([A-Za-z0-9._+-]+)", line)
        if not match:
            raise ValueError(f"{path}:{number}: expected '<sha256>  <archive>'")
        digests[match[2]] = match[1]
    return digests


def release_url(repository, version, target):
    return f"https://github.com/{repository}/releases/download/v{version}/{archive_name(version, target)}"


def digest_for(digests, version, target):
    name = archive_name(version, target)
    if name not in digests:
        raise ValueError(f"SHA256SUMS has no entry for {name}")
    return digests[name]


def homebrew_formula(version, digests, repository, description):
    blocks = []
    for os_name in ("macos", "linux"):
        arches = []
        for arch in ("arm", "intel"):
            target = HOMEBREW[(os_name, arch)]
            arches.append(
                f"    on_{arch} do\n"
                f"      url \"{release_url(repository, version, target)}\"\n"
                f"      sha256 \"{digest_for(digests, version, target)}\"\n"
                f"    end\n")
        blocks.append(f"  on_{os_name} do\n" + "".join(arches) + "  end\n")
    return (
        "# Generated by scripts/distribution.py from the release SHA256SUMS; do not edit.\n"
        "class Anytopdf < Formula\n"
        f"  desc \"{description}\"\n"
        f"  homepage \"https://github.com/{repository}\"\n"
        f"  version \"{version}\"\n"
        "  license any_of: [\"MIT\", \"Apache-2.0\"]\n"
        "\n" + "\n".join(blocks) +
        "\n"
        "  def install\n"
        "    bin.install \"anytopdf\"\n"
        "    libexec.install \"plugins\"\n"
        "    doc.install Dir[\"*.md\"]\n"
        "  end\n"
        "\n"
        "  def caveats\n"
        "    <<~EOS\n"
        "      Video, metadata, OCR and transcription use optional providers.\n"
        "      Install the ones you need:\n"
        "        brew install ffmpeg exiftool tesseract whisper-cpp\n"
        "      Bundled runtime plugins are opt-in. To transcribe audio and video with\n"
        "      anytopdf-plugin-whisper, add to your shell profile:\n"
        "        export ANYTOPDF_PLUGIN_PATH=\"#{opt_libexec}/plugins\"\n"
        "        export ANYTOPDF_WHISPER_MODEL=/path/to/ggml-base.en.bin\n"
        "      Then run `anytopdf doctor` to check what is available.\n"
        "    EOS\n"
        "  end\n"
        "\n"
        "  test do\n"
        "    assert_match version.to_s, shell_output(\"#{bin}/anytopdf --version\")\n"
        "    assert_match \"anytopdf.capabilities/1\",\n"
        "                 shell_output(\"#{bin}/anytopdf --no-plugins capabilities --json\")\n"
        + "".join(f"    assert_match \"\\\"protocol\\\":1\",\n"
                  f"                 shell_output(\"#{{libexec}}/plugins/{plugin} --anytopdf-manifest\")\n"
                  for plugin in PLUGINS) +
        "  end\n"
        "end\n")


def scoop_manifest(version, digests, repository, description):
    template_repository = f"https://github.com/{repository}/releases/download/v$version"
    return {
        "version": version,
        "description": description,
        "homepage": f"https://github.com/{repository}",
        "license": "MIT|Apache-2.0",
        "architecture": {
            arch: {
                "url": release_url(repository, version, target),
                "hash": digest_for(digests, version, target),
                "extract_dir": f"{NAME}-{version}-{target}",
            }
            for arch, target in SCOOP.items()
        },
        "bin": "anytopdf.exe",
        "notes": [
            "Bundled runtime plugins are opt-in. To transcribe audio and video, set",
            "ANYTOPDF_PLUGIN_PATH to $dir\\plugins and ANYTOPDF_WHISPER_MODEL to a",
            "whisper.cpp ggml model file.",
        ],
        "suggest": {"FFmpeg": "ffmpeg", "ExifTool": "exiftool", "Tesseract": "tesseract"},
        "checkver": "github",
        "autoupdate": {
            "architecture": {
                arch: {
                    "url": f"{template_repository}/{NAME}-$version-{target}.zip",
                    "hash": {"url": "$url.sha256"},
                    "extract_dir": f"{NAME}-$version-{target}",
                }
                for arch, target in SCOOP.items()
            }
        },
    }


def default_repository(root=ROOT):
    url = workspace_package(root)["repository"]
    match = re.fullmatch(r"https://github\.com/([\w.-]+/[\w.-]+?)(?:\.git)?/?", url)
    if not match:
        raise ValueError(f"workspace repository is not a GitHub URL: {url}")
    return match[1]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--checksums", type=Path, required=True, help="release SHA256SUMS file")
    parser.add_argument("--output", type=Path, required=True, help="directory for anytopdf.rb and anytopdf.json")
    parser.add_argument("--version", help="release version without the leading v (default: Cargo.toml)")
    parser.add_argument("--repository", help="GitHub owner/name (default: Cargo.toml repository)")
    args = parser.parse_args(argv)
    version = (args.version or workspace_package()["version"]).removeprefix("v")
    if not SEMVER.fullmatch(version):
        parser.error(f"invalid version: {version}")
    repository = args.repository or default_repository()
    if not re.fullmatch(r"[\w.-]+/[\w.-]+", repository):
        parser.error(f"invalid repository: {repository}")
    try:
        digests = read_checksums(args.checksums)
        description = cli_description()
        formula = homebrew_formula(version, digests, repository, description)
        manifest = scoop_manifest(version, digests, repository, description)
    except (OSError, ValueError) as error:
        parser.exit(1, f"distribution: {error}\n")
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / f"{NAME}.rb").write_text(formula, encoding="utf-8")
    (args.output / f"{NAME}.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(args.output / f"{NAME}.rb")
    print(args.output / f"{NAME}.json")


if __name__ == "__main__":
    main()
